name:                duden
version:             0.1.0
homepage:            https://gitlab.com/slotThe/duden
synopsis:            Query duden search results from within your terminal
license:             AGPL-3
author:              slotThe
maintainer:          slotThe <soliditsallgood@mailbox.org>
copyright:           2020  slotThe

default-extensions:
  - OverloadedStrings
  - BlockArguments
  - ScopedTypeVariables
  - NamedFieldPuns
  - LambdaCase
  - InstanceSigs
  - BangPatterns

ghc-options:
  -O2
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints
  -Widentities
  -Wmissing-local-signatures
  -Wmissing-export-lists
  -Wmissed-specialisations

library:
  source-dirs: lib

dependencies:
  - name: base
    mixin: hiding (Prelude)
  - base-prelude
  - containers
  - http-client
  - http-client-tls
  - async
  - text
  - bytestring
  - attoparsec
  - html-parse
  - html-parse-utils
  - optparse-applicative
  - optparse-applicative-cmdline-util

executables:
  duden:
    source-dirs: app
    main: Main.hs
    dependencies: duden
    ghc-options:
      -threaded
      -rtsopts
      -with-rtsopts=-N
