resolver: lts-19.0

packages:
  - .

extra-deps:
  - git: https://github.com/bgamari/html-parse.git
    commit: 52fa100da5d4d20ad3497b4a09a31b71528a10fb
  - git: https://gitlab.com/slotThe/html-parse-utils.git
    commit: 7401e85ebe4547a9a727bf659cae594d0080ae63
  - optparse-applicative-cmdline-util-0.2.0
