resolver: lts-21.0

packages:
  - .

extra-deps:
  - optparse-applicative-cmdline-util-0.2.0
  - html-parse-util-0.2.3
  - git: https://github.com/bgamari/html-parse.git
    commit: 4a46e25e518fa477de20bc72bc764697cdff6c3a
  - git: https://gitlab.com/slotThe/cmdline-util
    commit: c5d6e3832b38769be649b8dae2dd8f4659ead577

allow-newer: true
